#!/bin/bash
# Based on https://doc.owncloud.org/server/10.0/admin_manual/maintenance/backup.html.
# Expects as the only argument a path to an existing empty folder.
# In the specified folder creates the files necessary to restore a fresh installation of ownCloud to the state it had
# when this script was executed.
set -o errexit
set -o nounset
set -o pipefail

if [[ ("$#" -ne 1) || (! -d "$1") || "$(ls -A $1)" ]]; then
  echo "Error: The only argument must be an existing empty folder."
  exit 1
fi

echo "Backing up files..."
sudo tar --create --file=$1/owncloud-files.tar.gz --use-compress-program=pigz --directory=/var/www/html/owncloud config data
echo "Verifying files..."
sudo tar --compare --file=$1/owncloud-files.tar.gz --directory=/var/www/html/owncloud
echo "Backing up database..."
mysqldump --single-transaction -h localhost -u owncloud -p12345 owncloud > $1/owncloud-db-dump.sql
echo "Backup completed successfully."
