#!/bin/bash
# Based on https://doc.owncloud.org/server/10.0/admin_manual/maintenance/restore.html.
# Expects as the only argument a path to a folder containing the files created by the backup script.
# This will restore a fresh installation of ownCloud to the state it had when backup was executed.
set -o errexit
set -o nounset
set -o pipefail

if [ "$#" -ne 1 ] || [ ! -f "$1/owncloud-files.tar.gz" ] || [ ! -f "$1/owncloud-db-dump.sql" ]; then
  echo "Error: The only argument must be a folder containing the files created by the backup script."
  exit 1
fi

echo "This will delete all user data and then attempt to restore data from the backup."
read -p "Do you want to continue [y/N]? " answer

if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
  echo "Restore aborted."
  exit 0
fi

echo "Deleting current files..."
sudo rm -r /var/www/html/owncloud/config
sudo rm -r /var/www/html/owncloud/data
echo "Restoring files..."
sudo tar --extract --file=$1/owncloud-files.tar.gz --preserve-permissions --directory=/var/www/html/owncloud
echo "Restoring database..."
mysql -u owncloud -p12345 owncloud < $1/owncloud-db-dump.sql
echo "Restore completed successfully."
