#!/bin/bash
# Based on https://www.avoiderrors.net/owncloud-10-raspberry-pi-3-raspbian-stretch/
# and https://doc.owncloud.com/server/10.0/admin_manual/installation/source_installation.html.
# Assumes that setup1 has been executed successfully.
set -o errexit
set -o nounset
set -o pipefail

read -p "ownCloud admin username: " owncloud_admin_user
read -s -p "ownCloud admin password: " owncloud_admin_password

# Install multi-core compression, Apache and packages required by ownCloud
sudo apt-get install pigz apache2 mariadb-server libapache2-mod-php7.0 php7.0-gd php7.0-json php7.0-mysql php7.0-curl php7.0-intl php7.0-mcrypt php-imagick php7.0-zip php7.0-xml php7.0-mbstring --assume-yes
sudo systemctl start apache2
sudo systemctl enable apache2

# Install ownCloud
wget https://download.owncloud.org/community/owncloud-10.0.4.tar.bz2
tar --extract --verbose --file=owncloud-10.0.4.tar.bz2
rm owncloud-10.0.4.tar.bz2
sudo chown -R www-data:www-data owncloud
sudo mv owncloud /var/www/html

# Configure apache
sudo cp ./owncloud.conf /etc/apache2/sites-available/
sudo ln -s /etc/apache2/sites-available/owncloud.conf /etc/apache2/sites-enabled/owncloud.conf
sudo a2enmod rewrite
sudo a2enmod headers
sudo a2enmod env
sudo a2enmod dir
sudo a2enmod mime
sudo a2enmod ssl
sudo a2ensite default-ssl
sudo systemctl restart apache2

# Create mysql DB
sudo mysql -u "root" "-praspberry" < "create-db.sql"

# Configure ownCloud
current_directory=$PWD
cd /var/www/html/owncloud/
sudo -u www-data php occ maintenance:install --database "mysql" --database-name "owncloud" --database-user "owncloud" --database-pass "12345" --admin-user "$owncloud_admin_user" --admin-pass "$owncloud_admin_password"

# Add our IP address to the ownCloud trusted domains
ip_address=$(hostname -I | tr -d '[:space:]')
sudo -u www-data php occ config:system:set trusted_domains 0 --value=$ip_address

# The default option for background tasks (ajax) seems to never clear stale file locks (or at least takes a very long
# time). This is why we're using cron for background tasks.
# https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/background_jobs_configuration.html#cron-jobs
sudo -u www-data php occ background:cron
sudo crontab -u www-data -l | { cat; echo "*/15  *  *  *  * /usr/bin/php -f /var/www/html/owncloud/cron.php"; } | sudo crontab -u www-data -
cd $current_directory

if [ -x "$(command -v xdg-open)" ]; then
  # Open browser on Raspbian (doesn't work on Lite)
  xdg-open "http://$ip_address/owncloud"
else
  echo "Direct your web browser to: http://$ip_address/owncloud"
fi
