#!/bin/bash
# Based on https://www.avoiderrors.net/owncloud-10-raspberry-pi-3-raspbian-stretch/
# Assumes that setup2 will be executed after the reboot
set -o errexit
set -o nounset
set -o pipefail

# Set options that require reboot
sudo raspi-config nonint do_memory_split 32
sudo raspi-config nonint do_change_locale en_US.UTF-8
sudo reboot
